name: flutter_svg_converter
description: A web app that converts SVG source into Flutter Custom Painter canvas commands.
homepage: https://github.com/crystalboxes/flutter_svg_converter
version: 0.18.0

dependencies:
  xml: ^4.2.0
  vector_math: ^2.0.8
  meta: ^1.1.8
  dart_style: ^1.3.6
  path_parsing: ^0.1.4
  tuple: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  path: ^1.7.0
  test: ^1.14.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.2.0 <3.0.0'
  flutter: '>=1.18.0-6.0.pre <2.0.0'
